[package]
name = "hello_wasm"
version = "0.1.0"
authors = ["NewBobPlus <rschuhler@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stdweb = "0.4.20"
