<?php

$imgs = [
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
  "images/todo.png",
];

?>
